package com.xtbn.types.enums;

public enum DrawioXmlValidationErrorCode {
    EMPTY_XML,
    XML_SYNTAX_ERROR,
    ROOT_NOT_MXFILE,
    MISSING_DIAGRAM,
    MISSING_GRAPH_MODEL,
    MISSING_ROOT,
    MISSING_CELL_ID,
    DUPLICATE_CELL_ID,
    MISSING_ROOT_CELL_0,
    MISSING_ROOT_CELL_1,
    INVALID_PARENT,
    CELL_ROLE_CONFLICT,
    VERTEX_GEOMETRY_MISSING,
    VERTEX_COORDINATE_INVALID,
    VERTEX_SIZE_INVALID,
    EDGE_GEOMETRY_MISSING,
    EDGE_ENDPOINT_MISSING,
    EDGE_ENDPOINT_INVALID
}
