version: "3.8"

services:
  agenx-drawio-app:
    image: agenx-drawio-app:latest
    container_name: agenx-drawio-app
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8091
      MANAGEMENT_SERVER_PORT: 9091
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      AI_API_KEY: "${AI_API_KEY}"
      AI_API_BASE_URL: "${AI_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
      AI_COMPLETIONS_PATH: "${AI_COMPLETIONS_PATH:-chat/completions}"
      BAIDU_SEARCH_BASE_URI: "${BAIDU_SEARCH_BASE_URI:-http://appbuilder.baidu.com/v2/ai_search/mcp/}"
      BAIDU_SEARCH_API_KEY: "${BAIDU_SEARCH_API_KEY:-}"
    ports:
      - "8091:8091"
    expose:
      - "9091"
    volumes:
      - ./data/log:/data/log
    networks:
      - my-network

networks:
  my-network:
    external: true
